export const JobTitles = [
  "Accountant / Bookkeeper",
  "Admin / Operations",
  "Alpaca / Llama Ranch",
  "Animal Sanctuary",
  "Barn Hand",
  "Barn Manager",
  "Bison Ranch",
  "Butcher / Meat Processing",
  "Cattle Ranch",
  "Cook / Chef",
  "Dairy Ranch",
  "Dog Training / Kennel Ranch",
  "Equestrian",
  "Equine",
  "Family Ranch",
  "Farm Ranch",
  "Farrier / Horseshoeing",
  "Feedlot",
  "Fly Fishing",
  "Groundskeeping",
  "Guest / Dude Ranch",
  "Hay Ranch",
  "Horse Boarding Ranch",
  "Horse Care / Training",
  "Horse / Animal Rescue Ranch",
  "Horseback Riding / Trail Guide",
  "Housekeeping",
  "Hunting Ranch",
  "Loper / Cutting Horse",
  "Organic / Regenerative Ranch",
  "Outfitter",
  "Pen Rider",
  "Poultry / Chicken Ranch",
  "Private Ranch",
  "Ranch Caretaker",
  "Ranch Cowboy",
  "Ranch Foreman",
  "Ranch Hand",
  "Ranch Handyman / Maintenance",
  "Ranch Herdsman Jobs",
  "Ranch Jobs for Couples / Teams",
  "Ranch Jobs with Housing",
  "Ranch Manager",
  "Ranch Mechanic",
  "Ranch Technician",
  "Ranch Veterinarian",
  "Range Rider",
  "Resort Ranch",
  "Sales & Marketing",
  "Sheep / Goat Ranch",
  "Summer Ranch Jobs",
  "Timber Ranch",
  "Wait Staff / Kitchen Staff",
  "Wedding Ranch",
  "Winery / Vineyard Ranch",
  "Wrangler",
];

export const JobLocations = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California (North or South)",
  "Colorado",
  "Connecticut",
  "Delaware",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
];

export const JobExperience = [
  "0-1 years",
  "1-2 years",
  "2-3 years",
  "3-5 years",
  "5-7 years",
  "7-10 years",
  "10+ years",
];
